### ISSUE TITLE
Library code is not ready yet

### ISSUE THREAD

**Issue by artknight** [sqids/sqids-coldfusion#2]
I have tried using it and it does not seem to work!!

```
var sqids = new sqids({
   alphabet: "FxnXM1kBN6cuhsAvjW3Co7l2RePyY8DwaU04Tzt9fHQrqSVKdpimLGIJOgb5ZE"
})
var id = sqids.encode([417]) // "Ri0"
var numbers = sqids.decode(id) // []
```

**Comment by 4kimov** [comment]
Hi @artknight, it's _not_ marked as done on https://sqids.org/coldfusion

This is a work-in-progress, started by @timsayshey. We could definitely use some help from somebody getting this thru the finish line.

**Comment by 4kimov** [comment]
@artknight, new PR merged & website updated, thanks to the work of @bferdinandus 👍 

Closing this ticket, please open new ones as needed [for specific issues]
